# Generated by Django 2.2.28 on 2025-03-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapchef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Media',
            field=models.CharField(max_length=255),
        ),
    ]
