# Generated by Django 5.1.7 on 2025-03-11 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapchef', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeVideo',
        ),
    ]
