# Generated by Django 5.1.7 on 2025-03-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapchef', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='path/'),
        ),
    ]
