# Generated by Django 5.1.7 on 2025-03-25 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapchef", "0002_alter_list_id_alter_post_id_alter_review_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
