# Generated by Django 5.1.7 on 2025-03-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scrapchef", "0003_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="Media",
            field=models.ImageField(upload_to="post_media/"),
        ),
    ]
