# Generated by Django 5.1.7 on 2025-03-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapchef', '0003_userprofile_delete_user_alter_list_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
